language: python
cache: pip
python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
env:
  - INFLUXDB_VERSION=0.9.6.1
before_install:
  - wget https://s3.amazonaws.com/influxdb/influxdb_${INFLUXDB_VERSION}_amd64.deb
  - sudo dpkg -i influxdb_${INFLUXDB_VERSION}_amd64.deb
  - sudo /etc/init.d/influxdb start
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install coverage coveralls
script:
  - python setup.py nosetests --with-coverage --cover-package=graphite_influxdb
notifications:
  email:
    on_failure: change
after_success:
  - coveralls
services:
  - memcached
