language: python
cache: pip
python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
env:
  - INFLUXDB_VERSION=1.0.0~rc2
before_install:
  - wget https://dl.influxdata.com/influxdb/releases/influxdb_${INFLUXDB_VERSION}_amd64.deb
  - sudo dpkg -i influxdb_${INFLUXDB_VERSION}_amd64.deb
  - sudo /etc/init.d/influxdb start
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install coverage coveralls
script:
  - nosetests --with-coverage --cover-package=graphite_influxdb
  - nosetests --with-coverage --cover-package=graphite_influxdb tests/test_log1.py
  - nosetests --with-coverage --cover-package=graphite_influxdb tests/test_log2.py
notifications:
  email:
    on_failure: change
after_success:
  - coveralls
services:
  - memcached
