language: python
cache: pip
python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
  - pypy
  - pypy3
env:
  - INFLUXDB_VERSION=1.0.2
before_install:
  - wget https://dl.influxdata.com/influxdb/releases/influxdb_${INFLUXDB_VERSION}_amd64.deb
  - sudo dpkg -i influxdb_${INFLUXDB_VERSION}_amd64.deb
  - sudo /etc/init.d/influxdb start
install:
  - pip install -r requirements.txt
  - pip install coverage coveralls
script:
  - nosetests --with-coverage --cover-package=influxgraph
  - pip install statsd
  - nosetests --with-coverage --cover-package=influxgraph tests/test_influxdb_integration.py
notifications:
  email:
    on_failure: change
after_success:
  - coveralls
services:
  - memcached
