language: python
python:
  - 2.6
  - 2.7
  - 3.4
env:
  - INFLUXDB_VERSION=0.9.2-rc1
before_install:
  - wget https://s3.amazonaws.com/influxdb/influxdb_${INFLUXDB_VERSION}_amd64.deb
  - sudo dpkg -i influxdb_${INFLUXDB_VERSION}_amd64.deb
  - sudo /etc/init.d/influxdb start
  - sleep 5
install:
  - pip install -r requirements.txt
  - pip install coverage coveralls
# Explicitly set UTC timezone as InfluxDB returns UTC time stamps
script: TZ="UTC" nosetests --with-coverage --cover-package=graphite_influxdb
notifications:
  email:
    on_failure: change
after_success:
  - coveralls
